#!/bin/bash

function usage() {
  cat <<EOM
使用方法: $(basename "$0") [OPTION]...
    -p          pacmanのみ実行
    -y		'y'の入力をスキップします
    -h          ヘルプを表示します
    -c     アップデート後、システムをクリーンアップします
           ただし、ダウングレードが難しくなるため、推奨しません。

EOM
}

function update_sys() {
    sudo pacman -Syu $PACUP_YES
}

function update_aur() {
    yay -Syu
}

function update_flatpak() {
    flatpak update $PACUP_FLATPAK_YES
}

function clean() {
    yay -Yc
    sudo pacman -Sc
}

function update() {
    if [PACUP_PAC == true]; then
        update_sys
    else
        update_sys
        update_aur
        update_flatpak
    fi
    if [PACUP_CLEAN == true]; then
        clean
    fi
}

while (($#>0)); do
  case $1 in
    p|-p|--pacman)
      PACUP_PAC=true
      ;;
    y|-y|--yes)
      PACUP_YES=" --noconfirm"
      PACUP_FLATPAK_YES=" -y"
      ;;
    h|-h|--help)
      usage
      exit 0
      ;;
    c|-c|--clean)
      PACUP_CLEAN=true
      ;;
    *)
      usage
      exit 1
      ;;
  esac
shift
done

update()

sleep 3

exit 0
